services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    mysql:
        image: mysql:8.0
        volumes:
            - ./db/data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - TZ=Asia/Seoul
            - MYSQL_DATABASE=promotion
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_USER=hiimdongho
            - MYSQL_PASSWORD=1234